### ISSUE TITLE
Where did all your guides go?

### ISSUE THREAD

**Issue by Jonseed** [Pelayo-Chacon/stable-diffusion-resources#1]
Hey, your guides were great. Where did they all go?

**Comment by Pelayo-Chacon** [comment]
I was being lambasted by a few people last night after someone popped my setup guide into the first post of a thread, so I made the decision to swap the URLs to privatize them for people I know IRL rather than continually deal with getting into arguments with strangers.

I forgot I put this library up though, so if you're still interested, check back in a bit and I'll post them here.

**Comment by Pelayo-Chacon** [comment]
@Jonseed All guides are now available from this repo. I have to make some updates at a later date since I purged a few files, but the bulk of the information is there. I'll also set up a location for the textual inversion model I made, with hopefully more to come. 

If there's anything you'd like to see, let me me know. Feel free to share this as you please.

**Comment by Jonseed** [comment]
@Pelayo-Chacon awesome!! Thank you! I think these guides are great. Great work. Keep it up. There are those like me who really appreciate it. Haters gonna hate. Just ignore them. Thanks again!

**Comment by Pelayo-Chacon** [comment]
Thank you - I really appreciate that! I'll absolutely keep uploading anything I work on to this repo.

I'll hopefully have some time this weekend to get the current guides updated to reference newer features. I'm also planning to do some cross testing of standard SD upscaling vs. the alternate method (initial theory being one is better for landscapes and one for anthropomorphic figures), and hopefully take a stab at outpainting when I have the chance.
